<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Empresa;
use AppBundle\Entity\Publicacion;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends \Doctrine\ORM\EntityRepository {

	function getCantidadComentariosPorElemento( $elemento ) {
		$qb = $this->createQueryBuilder( 'c' );
		if ( $elemento instanceof Empresa ) {
			$qb->join( 'c.empresa', 'emp' )
			   ->where( 'emp = :param1' )
			   ->setParameter( 'param1', $elemento );
		} elseif ( $elemento instanceof Publicacion ) {
			$qb->join( 'c.publicacion', 'pub' )
			   ->where( 'pub = :param1' )
			   ->setParameter( 'param1', $elemento );
		}
		$cant = $qb->getQuery()->getResult();

		return count( $cant );

	}

	public function findUltimosComentariosByEmpresa( $empresa ) {
		$qb = $this->createQueryBuilder( 'c' );

		$qb->join( 'c.empresa', 'emp' )
		   ->where( 'emp = :empresa' )
		   ->setParameter( 'empresa', $empresa );

		$qb->orderBy( 'c.fechaCreacion', 'DESC' );
		$qb->setMaxResults( 10 );

		return $qb->getQuery()->getResult();

	}

	public function findActivosByEmpresa( $empresa ) {
		$qb = $this->createQueryBuilder( 'c' );

		$qb->join( 'c.empresa', 'emp' )
		   ->where( 'emp = :empresa' )
		   ->andWhere( 'c.activo = true' )
		   ->setParameter( 'empresa', $empresa );

		return $qb->getQuery()->getResult();
	}

	public function findActivosByPublicacion( $publicacion ) {
		$qb = $this->createQueryBuilder( 'c' );

		$qb->join( 'c.publicacion', 'emp' )
		   ->where( 'emp = :publicacion' )
		   ->andWhere( 'c.activo = true' )
		   ->setParameter( 'publicacion', $publicacion );

		return $qb->getQuery()->getResult();
	}
}
