<?php

namespace AppBundle\Repository;

/**
 * DispositivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DispositivoRepository extends \Doctrine\ORM\EntityRepository
{
}
