<?php

namespace AppBundle\Repository;

/**
 * DispositivoPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DispositivoPersonaRepository extends \Doctrine\ORM\EntityRepository
{
}
