<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository {

	public function findBySlugCategoria( $slug ) {


		$qb = $this->createQueryBuilder( 'e' );

		$qb->join( 'e.categoriaEmpresa', 'ce' )
		   ->join( 'ce.categoria', 'c' );

		$qb->where( 'c.slug = :slug' )
		   ->setParameter( 'slug', $slug );

		return $qb->getQuery()->getResult();


	}

}
