<?php

namespace AppBundle\Repository;

/**
 * FavoritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoritoRepository extends \Doctrine\ORM\EntityRepository
{
}
