<?php

namespace AppBundle\Repository;

/**
 * FavoritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoritoRepository extends \Doctrine\ORM\EntityRepository {

	public function findPublicacionesFavoritas( $persona ) {
		$qb = $this->createQueryBuilder( 'f' )
		;

		$qb->join( 'f.publicacion', 'p' );

		$qb->where( 'p.fechaInicio <= :fechaActualMax' )
		   ->andWhere( 'p.fechaFin >= :fechaActualMin' )
		   ->andWhere( 'p.publicado = true' )
		   ->andWhere( 'f.persona = :persona' );

		$fechaActual = new \DateTime( 'now' );

		$qb->setParameter( 'fechaActualMax', $fechaActual->format( 'Y-m-d' ) . " 23:59:59" );
		$qb->setParameter( 'fechaActualMin', $fechaActual->format( 'Y-m-d' ) . " 00:00:00" );
		$qb->setParameter( 'persona', $persona );

		return $qb->getQuery()->getResult();
	}

	public function findEmpresasFavoritas( $persona ) {
		$qb = $this->createQueryBuilder( 'f' )
		;

		$qb->join( 'f.empresa', 'e' );

		$qb
		   ->andWhere( 'f.persona = :persona' );

		$fechaActual = new \DateTime( 'now' );

		$qb->setParameter( 'persona', $persona );

		return $qb->getQuery()->getResult();
	}
}
