<?php

namespace AppBundle\Repository;

/**
 * FechaPublicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FechaPublicacionRepository extends \Doctrine\ORM\EntityRepository
{
}
