<?php

namespace AppBundle\Repository;

/**
 * FotoPersonaEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FotoPersonaEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
}
