<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HotelAgenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelAgenciaRepository extends EntityRepository
{
}
