<?php

namespace AppBundle\Repository;

/**
 * LikesSharePorElementoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikesSharePorElementoRepository extends \Doctrine\ORM\EntityRepository
{
}
