<?php

namespace AppBundle\Repository;

/**
 * NoticiaInternaEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaInternaEmpresaRepository extends \Doctrine\ORM\EntityRepository {
	public function findByEmpresa( $empresa ) {

		$qb = $this->createQueryBuilder( 'nie' );

		$qb->where( 'nie.empresa = :empresa' )
		   ->andWhere( $qb->expr()->andx(
			   $qb->expr()->isNull( 'nie.volverAMostrar' )
		   ) )
		   ->orWhere( 'nie.volverAMostrar = false' )
		   ->setParameter( 'empresa', $empresa );

		return $qb->getQuery()->getResult();
	}
}
