<?php

namespace AppBundle\Repository;

/**
 * NoticiaInternaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaInternaRepository extends \Doctrine\ORM\EntityRepository {
	public function getNoticiasActuales() {
		$qb = $this->createQueryBuilder( 'ni' );

		$qb->where( 'ni.visibleDesde <= :fechaActual' )
		   ->andWhere( 'ni.visibleHasta >= :fechaActual' );
		$fechaActual = new \DateTime( 'now' );
		$qb->setParameter( 'fechaActual', $fechaActual->format( 'Y-m-d' ) );


		return $qb->getQuery()->getResult();

	}

}
