<?php

namespace AppBundle\Repository;

/**
 * NoticiaInternaEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaInternaEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
}
