<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaRepository extends EntityRepository {
	public function findByEmpresa( $empresa ) {

		$qb = $this->createQueryBuilder( 'n' );

		$qb->join( 'n.noticiaEmpresa', 'ne' )
		   ->join( 'ne.empresa', 'e' )
		   ->where( 'ne.id = :empresaId' )
		   ->setParameter( 'empresaId', $empresa );

		return $qb->getQuery()->getResult();

	}

}
