<?php

namespace AppBundle\Repository;

/**
 * PerfilPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilPersonaRepository extends \Doctrine\ORM\EntityRepository
{
}
