<?php

namespace AppBundle\Repository;

/**
 * PersonaOndaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaOndaRepository extends \Doctrine\ORM\EntityRepository
{
}
