<?php

namespace AppBundle\Repository;

/**
 * PlanEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanEmpresaRepository extends \Doctrine\ORM\EntityRepository {
	public function findPlanActivoByEmpresa( $empresa ) {

		$qb = $this->createQueryBuilder( 'pe' );

		$qb->join( 'pe.empresa', 'emp' );

		$qb->where( 'pe.vencimiento >= :fechaActual' )
		   ->andWhere( 'emp.id = :empresa' )
		   ->andWhere( 'pe.activo = :activo' );

		$fechaActual = new \DateTime( 'now' );

		$qb->setParameter( 'fechaActual', $fechaActual->format( 'Y-m-d' ) );
		$qb->setParameter( 'empresa', $empresa );
		$qb->setParameter( 'activo', true );


		return $qb->getQuery()->getResult();

	}
}
