<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Empresa;
use Doctrine\ORM\EntityRepository;

/**
 * PublicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionRepository extends EntityRepository {
	public function findAllByEmpresa( $empresa ) {
		$qb = $this->createQueryBuilder( 'p' );

		$qb->join( 'p.publicacionEmpresa', 'pe' );

		if ( is_integer( $empresa ) ) {
			$qb->join( 'pe.empresa', 'e' )
			   ->where( 'e.id = :empresa' )
			   ->setParameter( 'empresa', $empresa );
		} else if ( $empresa instanceof Empresa ) {
			$qb->where( 'pe.empresa = :empresa' )
			   ->setParameter( 'empresa', $empresa );
		}


		return $qb->getQuery()->getResult();

	}
}
