<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RubroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubroRepository extends EntityRepository {
	public function getByLocale( $locale ) {

		$qb = $this->createQueryBuilder( 'r' );
		switch ( $locale ) {
			case 'es':
				$qb->select( 'r.nombre' );
				break;
			case 'en':
				$qb->select( 'r.en' );
				break;
			case 'pt':
				$qb->select( 'r.pt' );
				break;
			default:
				$qb->select( 'r.nombre' );
		}
		$qb->where( 'r.activo = true' );

		return $qb->getQuery()->getResult();

	}
}
