<?php

namespace AppBundle\Repository;

/**
 * ThumbRubroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThumbRubroRepository extends \Doctrine\ORM\EntityRepository
{
}
