<?php

namespace AppBundle\Repository;

/**
 * TipoEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
