<?php

namespace AppBundle\Repository;

/**
 * WebConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
