imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: easyadmin/ }
    - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    site_name: 'EvenProm'
    languages: "(es|en|pt)"
    app.path.empresas_image: /uploads/images/empresas
    app.path.publicaciones_image: /uploads/images/publicaciones
    app.path.noticias_image: /uploads/images/noticias
    app.path.noticias_internas_image: /uploads/images/noticias_internas
    app.path.planes_image: /uploads/images/planes
    app.path.personas_image: /uploads/images/personas
    app.path.rubros_image: /uploads/images/rubros
    app.path.imagen_usuario_empresa_image: /uploads/images/imagen_usuario_empresa

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        site_name: %site_name%
        version: %version%
        fb_app_id: %fb_client_id%
        g_app_id: %g_client_id%
        g_api_key: %g_api_key%
    form_themes:
        - 'AppBundle:Form:custom_widgets.html.twig'
#        - 'bootstrap_3_layout.html.twig'
#        - 'VichUploaderBundle:Form:fields.html.twig'
        - 'AppBundle:Form:image_widget.html.twig'
        - 'UtilBundle:Form:fields.html.twig'
        - 'UtilBundle:Form:tetranz_select2entity_widget.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#doctrine extentions
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            translatable: true
            timestampable: true
            blameable: true
            sluggable: true

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: 'AppBundle:Menu:knp_menu.html.twig'
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

#fos user
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UsuariosBundle\Entity\Usuario

#vich uploader
vich_uploader:
    db_driver: orm
    mappings:
        empresas_image:
            uri_prefix:         %app.path.empresas_image%
            upload_destination: %kernel.root_dir%/../web/uploads/images/empresas
            namer:              vich_uploader.namer_origname
        publicaciones_image:
            uri_prefix:         %app.path.publicaciones_image%
            upload_destination: %kernel.root_dir%/../web/uploads/images/publicaciones
            namer:              vich_uploader.namer_origname
        noticias_image:
            uri_prefix:         %app.path.noticias_image%
            upload_destination: %kernel.root_dir%/../web/uploads/images/noticias
            namer:              vich_uploader.namer_origname
        noticias_internas_image:
            uri_prefix:         %app.path.noticias_internas_image%
            upload_destination: %kernel.root_dir%/../web/uploads/images/noticias_internas
            namer:              vich_uploader.namer_origname
        planes_image:
            uri_prefix:         %app.path.planes_image%
            upload_destination: %kernel.root_dir%/../web/uploads/images/planes
            namer:              vich_uploader.namer_origname
        personas_image:
            uri_prefix:         %app.path.personas_image%
            upload_destination: %kernel.root_dir%/../web/uploads/images/personas
            namer:              vich_uploader.namer_origname
        rubros_image:
            uri_prefix:         %app.path.rubros_image%
            upload_destination: %kernel.root_dir%/../web/uploads/images/rubros
            namer:              vich_uploader.namer_origname
        imagen_usuario_empresa_image:
            uri_prefix:         %app.path.imagen_usuario_empresa_image%
            upload_destination: %kernel.root_dir%/../web/uploads/images/imagen_usuario_empresa
            namer:              vich_uploader.namer_origname

ivory_ck_editor:
    default_config: my_config
    configs:
        my_config:
            toolbar: [ ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],  ['Bold', 'Italic', 'Strike', '-', 'RemoveFormat'], '/', ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote'], ['Styles', 'Format']  ]

#fos rest
fos_rest:
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    body_converter:
        enabled: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            # ... previous rules declarations
#            - { path: '^/admin', stop: true }  # <-- add this line
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

#nelmio
nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
        paths:
            '^/api/':
                allow_origin: ['*']
                allow_headers: ['*']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/':
                origin_regex: true
                allow_origin: ['^http://localhost:[0-9]+']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']

hwi_oauth:
    connect:
        confirmation: true
#        registration_form: fos_user.registration.form
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
#            google: googleId
    resource_owners:
        # Facebook Access
        facebook:
            type:                facebook
            client_id:           %fb_client_id%
            client_secret:       %fb_client_secret%
            scope:               "public_profile"
            infos_url:           'https://graph.facebook.com/me?fields=email,first_name,last_name,id,picture'
            options:
                display: popup
        # Google Access
        google:
            type:                google
            client_id:           %g_client_id%
            client_secret:       %g_client_secret%
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            options:
                display: popup
    firewall_name: secured_area

#select 2
#util:
#    tetranz_select2_entity:
#        minimum_input_length: 2
#        page_limit: 8
#        allow_clear: true
#        delay: 500
#        language: %locale%
#        cache: false
#        cache_timeout: 0
#        scroll: true
