fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: |en|es|pt

easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /{_locale}/admin
    requirements:
        _locale: |en|es|pt


ubicacion_bundle:
    resource: "@UbicacionBundle/Resources/config/routing.yml"
    prefix: /ubicacion

rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api