_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# HWIOAuthBundle
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

# We override this part of the routing
hwi_oauth_connect:
     resource: "@UsuariosBundle/Resources/config/routing/connect.yml"
     prefix: /connect

facebook_login:
    path: /connect/check-facebook

google_login:
    path: /connect/check-google

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/empresa-admin
    requirements:
        _locale: |en|es|pt

public:
    resource: "@AppBundle/Resources/config/routing/public.yml"
    prefix:   /{_locale}
    requirements:
        _locale: |en|es|pt

easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /{_locale}/admin
    requirements:
        _locale: |en|es|pt


ubicacion_bundle:
    resource: "@UbicacionBundle/Resources/config/routing.yml"
    prefix: /ubicacion

rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api