security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:      ^/oauth/v2/token
            security:     false

#        api:
#            pattern:    ^/api(?!/registrars)
#            fos_oauth:  true
#            stateless:  true

        main:
            pattern: ^/
            anonymous: true
            logout: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            oauth:
                resource_owners:
                    facebook:           "/connect/check-facebook"
                    google:             "/connect/check-google"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
#                    service: hwi_oauth.user.provider
#                    service: hwi_oauth.user.provider.fosub_bridge
                    service: my_user_provider

    access_control:
#        - { path: ^/api/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/registrars, role: ROLE_PERSONA }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%languages%/^, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%languages%/admin/, role: ROLE_ADMIN }
        - { path: ^/%languages%/empresa/registrar, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%languages%/persona/registrar, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%languages%, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/%languages%/empresa, role: ROLE_EMPRESA }
        - { path: ^/%languages%/empresa-admin, role: ROLE_EMPRESA }
        - { path: ^/%languages%/persona, role: ROLE_PERSONA }
#        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%languages%/, role: IS_AUTHENTICATED_FULLY }