get_sub_rubros:
    path: /get_sub_rubros
    defaults: { _controller: "AppBundle:Ajax:getSubRubros" }

get_categorias:
    path: /get_categorias
    defaults: { _controller: "AppBundle:Ajax:getCategorias" }

ver_publicacion:
    path: /ver_publicacion
    defaults: { _controller: "AppBundle:Ajax:verPublicacion" }

comentar_perfil_empresa:
    path: /comentar_perfil_empresa/{empresaId}/{personaId}
    defaults: { _controller: "AppBundle:Ajax:comentarPerfilEmpresa" }

favear_empresa:
    path: /favear_empresa
    defaults: { _controller: "AppBundle:Ajax:favearEmpresa" }

favear_publicacion:
    path: /favear_publicacion
    defaults: { _controller: "AppBundle:Ajax:favearPublicacion" }
