comentarios_index:
    path:     /
    defaults: { _controller: "AppBundle:Comentario:index" }
    methods:  GET

comentarios_publicacion_index:
    path:     /publicacion/{id}
    defaults: { _controller: "AppBundle:Comentario:verComentariosPublicacion" }
    methods:  GET

comentarios_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Comentario:show" }
    methods:  GET



