empresa_index:
    path:     /
    defaults: { _controller: "AppBundle:Empresa:index" }
    methods:  GET

empresa_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Empresa:show" }
    methods:  GET

empresa_new:
    path:     /new
    defaults: { _controller: "AppBundle:Empresa:new" }
    methods:  [GET, POST]

empresa_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Empresa:edit" }
    methods:  [GET, POST]

empresa_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Empresa:delete" }
    methods:  DELETE

empresa_registrar:
    path:     /registrar
    defaults: { _controller: "AppBundle:Empresa:registrar" }
    methods:  [GET, POST]

empresa_perfil:
    path:     /perfil
    defaults: { _controller: "AppBundle:Empresa:perfil" }
    methods:  [GET, POST]