app_index:
    path:     /
    defaults: { _controller: "AppBundle:Default:indexApp" }
    methods:  [GET]

sitios_index:
    path:     /sitios
    defaults: { _controller: "AppBundle:Default:indexSitios" }

app_perfil_empresa:
    path:     /{id}/sitios
    defaults: { _controller: "AppBundle:Default:sitios" }

publicacion_public_show:
    path:     /#publicacion/{id}
#    defaults: { _controller: "AppBundle:Publicacion:redirectFb" }
    methods:  [GET]

#publicacion_public_show_23:
#    path:     /%23publicacion/{id}
#    defaults: { _controller: "AppBundle:Publicacion:redirectFb" }
#    methods:  [GET]