sitios_index:
    path:     /sitios
    defaults: { _controller: "AppBundle:Default:indexSitios" }

app_perfil_empresa:
    path:     /{id}/sitios
    defaults: { _controller: "AppBundle:Default:sitios" }

publicacion_show:
    path:     /publicacion/{id}/show
    defaults: { _controller: "AppBundle:Publicacion:show" }
    methods:  [GET]