favorito :
  type: rest
  resource:     "@AppBundle/Controller/Rest/FavoritosRestController.php"
  name_prefix:  api_

usuario :
  type: rest
  resource:     "@AppBundle/Controller/Rest/UsuariosRestController.php"
  name_prefix:  api_

persona :
  type: rest
  resource:     "@AppBundle/Controller/Rest/PersonasRestController.php"
  name_prefix:  api_

onda :
  type: rest
  resource:     "@AppBundle/Controller/Rest/OndasRestController.php"
  name_prefix:  api_

ubicacion :
  type: rest
  resource:     "@AppBundle/Controller/Rest/UbicacionRestController.php"
  name_prefix:  api_

categorias :
  type: rest
  resource:     "@AppBundle/Controller/Rest/CategoriasRestController.php"
  name_prefix:  api_

registro_llamada :
  type: rest
  resource:     "@AppBundle/Controller/Rest/RegistroLlamadaEmpresaRestController.php"
  name_prefix:  api_

noticias :
  type: rest
  resource:     "@AppBundle/Controller/Rest/NoticiasRestController.php"
  name_prefix:  api_

empresas :
  type: rest
  resource:     "@AppBundle/Controller/Rest/EmpresasRestController.php"
  name_prefix:  api_

publicaciones :
  type: rest
  resource:     "@AppBundle/Controller/Rest/PublicacionesRestController.php"
  name_prefix:  api_
