app_noticia_interna:
    resource: "@AppBundle/Resources/config/routing/noticiainterna.yml"
    prefix:   /noticia_interna

app_noticias:
    resource: "@AppBundle/Resources/config/routing/noticia.yml"
    prefix:   /noticias

app_publicaciones:
    resource: "@AppBundle/Resources/config/routing/publicacion.yml"
    prefix:   /publicaciones

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_empresa:
    resource: "@AppBundle/Resources/config/routing/empresa.yml"
    prefix:   /empresa

app_ajax:
    resource: "@AppBundle/Resources/config/routing/ajax.yml"
    prefix:   /ajax

