#easy admin
easy_admin:
    site_name: %site_name%
    entities:
        Pais:
            class: Matudelatower\UbicacionBundle\Entity\Pais
        Provincia:
            class: Matudelatower\UbicacionBundle\Entity\Provincia
        Departamento:
            class: Matudelatower\UbicacionBundle\Entity\Departamento
        Localidad:
            class: Matudelatower\UbicacionBundle\Entity\Localidad

    design:
        brand_color: '#367fa9'
        menu:
            - Empresa
            - Categoria
            - Onda
            - { label: 'Tipo Publicación', entity: TipoPublicacion }
            - label: 'Ubicación'
              children:
                  - 'Pais'
                  - 'Provincia'
                  - 'Departamento'
                  - 'Localidad'
            - 'Usuario'
            - { label: 'Cerrar Sesión', route: 'fos_user_security_logout', icon: 'sign-out' }
#
#    assets:
#        js:
#            - 'bundles/app/js/app.js'
