easy_admin:
    entities:
        Departamento:
            class: Matudelatower\UbicacionBundle\Entity\Departamento
            form:
                fields:
                    - { property: 'descripcion' }
                    - { property: 'codigo' }
                    - { property: 'provincia', type: 'entity', type_options: { class: 'Matudelatower\UbicacionBundle\Entity\Provincia', attr: { class: 'select2' }} }
            edit:
                title:  'Editar Departamento'
            new:
                title:  'Alta Departamento'
            list:
                title:  'Departamento'