easy_admin:
    entities:
        HotelAgencia:
            class: AppBundle\Entity\HotelAgencia
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'activo' }
            edit:
                title:  'Editar Hoteles y Agencias'
            new:
                title:  'Alta Hoteles y Agencias'
            list:
                title:  'Hoteles y Agencias'