easy_admin:
    entities:
        Localidad:
            class: Matudelatower\UbicacionBundle\Entity\Localidad
            form:
                fields:
                    - { property: 'descripcion' }
                    - { property: 'codigo' }
                    - { property: 'codigoPostal' }
                    - { property: 'latitud' }
                    - { property: 'longitud' }
                    - { property: 'poblacion' }
                    - { property: 'departamento', type: 'entity', type_options: { class: 'Matudelatower\UbicacionBundle\Entity\Departamento', attr: { class: 'select2' }} }
            edit:
                title:  'Editar Localidad'
            new:
                title:  'Alta Localidad'
            list:
                title:  'Localidad'