easy_admin:
    entities:
        Onda:
            class: AppBundle\Entity\Onda
            list:
                actions: ['-delete']
            show:
                actions: ['-delete']
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'pt',type: 'text', type_options:{ label: 'Nombre en Portuges'} }
                    - { property: 'en',type: 'text', type_options:{ label: 'Nombre en Ingles'} }
                    - { property: 'descripcion' }
                    - { property: 'activo' }
                actions: ['-delete']
            edit:
                title:  'Editar Onda'
            new:
                title:  'Alta Onda'
            list:
                title:  'Onda'