easy_admin:
    entities:
        Persona:
            class: AppBundle\Entity\Persona
            form:
                fields:
                    - { property: 'nombre',  type_options: { disabled: true }  }
                    - { property: 'apellido', type_options: { disabled: true }  }
            edit:
                title:  'Editar Persona'
            new:
                title:  'Alta Persona'
            list:
                title:  'Personas'
                fields:
                    - { property: 'nombre' }
                    - { property: 'apellido' }
#                    - { property: 'localidad' }
#                    - { property: 'mail' }
#                    - { property: 'telefono' }