easy_admin:
    entities:
        PlanEmpresa:
            class: AppBundle\Entity\PlanEmpresa
            form:
                fields:
                    - { property: 'vencimiento' }
                actions: ['-delete']
            edit:
                title:  'Editar Subscripción'
            new:
                title:  'Alta Subscripción'
            list:
                title:  'Subscripción'
                actions: ['-delete']