easy_admin:
    entities:
        PlanEmpresa:
            class: AppBundle\Entity\PlanEmpresa
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'valor' }
                    - { property: 'periodo', label: 'Periodo (en Dias)' }
                    - { property: 'imageFile', type: 'vich_image' }