easy_admin:
    entities:
        Provincia:
            class: Matudelatower\UbicacionBundle\Entity\Provincia
            form:
                fields:
                    - { property: 'descripcion' }
                    - { property: 'codigo' }
                    - { property: 'pais', type: 'entity', type_options: { class: 'Matudelatower\UbicacionBundle\Entity\Pais', attr: { class: 'select2' }} }
            edit:
                title:  'Editar Provincia'
            new:
                title:  'Alta Provincia'
            list:
                title:  'Provincia'