easy_admin:
    entities:
        Rubro:
            class: AppBundle\Entity\Rubro
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'iconoWeb', type_options: { attr: { class: 'iconpicker' }} }
                    - { property: 'activo' }
            edit:
                title:  'Editar Rubro'
            new:
                title:  'Alta Rubro'
            list:
                title:  'Rubro'