easy_admin:
    entities:
        SubRubro:
            class: AppBundle\Entity\SubRubro
            form:
                fields:
                    - { property: 'rubro', type: 'entity', type_options: { class: 'AppBundle\Entity\Rubro', attr: { class: 'select2' }} }
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'activo' }
            edit:
                title:  'Editar Sub Rubro'
            new:
                title:  'Alta Sub Rubro'
            list:
                title:  'Sub Rubro'