easy_admin:
    entities:
        TipoPublicacion:
            class: AppBundle\Entity\TipoPublicacion
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'slug' }
                    - { property: 'activo' }