easy_admin:
    entities:
        TipoPublicacion:
            class: AppBundle\Entity\TipoPublicacion
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'activo' }
            edit:
                title:  'Editar Tipo Publicacion'
            new:
                title:  'Alta Tipo Publicacion'
            list:
                title:  'Tipo Publicacion'