parameters:
        my_user_provider.class: UsuariosBundle\Security\Core\User\FOSUBUserProvider

services:
#    usuarios.example:
#        class: UsuariosBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    usuario.form.group:
        class: UsuariosBundle\Form\GrupoType
        tags:
            - { name: form.type, alias: usuarios_bundle_grupo_type }

    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebookId, google: googleId}]